### ISSUE TITLE
Clean the AnubisDB database

### ISSUE THREAD

**Issue by shelld3v** [jonluca/Anubis-DB#51]
I have submitted 2 PRs: https://github.com/jonluca/Anubis-DB/pull/50 and https://github.com/jonluca/Anubis-DB/pull/48.
Those PRs perform validation against subdomains received and so no more saving garbage in the future. But, since Anubis has been running for a while, dirty results in past still exist in the database, for example: https://jonlu.ca/anubis/subdomains/ui.com
I believe we need to clean up all results in the db.

Thank you for running such a great resource

**Comment by shelld3v** [comment]
@jonluca Can you delete data at https://jonlu.ca/anubis/subdomains/ui.com?

**Comment by jonluca** [comment]
Good idea. I've pushed up some cleaner code - I originally wrote this when I was in college, and it definitely isn't production grade code. 

I'll look into cleaning up the database as well.

**Comment by jonluca** [comment]
Done with code changes
